one = export blah="I was set!"; echo $$blah

# "define" is actually just a list of commands
define two
export blah=set
echo $$blah
endef

define three
blah=hehe && echo $$blah
endef
# One and two are different.

all:
	@echo "This prints 'I was set'"
	@$(one)
	@echo "This does not print 'I was set' because each command runs in a separate shell"
	@$(two)
	@$(three)
