with_spaces = hello   # with_spaces has many spaces after "hello"
after = $(with_spaces)there

nullstring =
space = $(nullstring) # Make a variable with a single space.

myspace = " "

all:
	@echo "$(after)"
	@echo start"$(space)"end
	@echo start"$(myspace)"end
